[project]
name = "sav"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "polars>=1.25.2",
    "streamlit>=1.43.2",
]
